SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768

PLAYER_WIDTH = 50
PLAYER_HEIGHT = 50

BUTTON_WIDTH = 100
BUTTON_HEIGHT = 50

BUTTON_DIMENSIONS = (
    (SCREEN_WIDTH / 2) - PLAYER_WIDTH,
    50,
    BUTTON_WIDTH,
    BUTTON_HEIGHT,
)
